# Generated by Django 3.2.25 on 2024-04-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0002_auto_20240422_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('update_time', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='UpdateTime',
        ),
        migrations.AlterField(
            model_name='indexs',
            name='father_url',
            field=models.URLField(),
        ),
    ]
