# Generated by Django 3.2.25 on 2024-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0003_auto_20240422_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=10)),
                ('cityurl', models.URLField()),
                ('WeatherUpdateDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Indexs',
        ),
        migrations.DeleteModel(
            name='ProvinceUpdate',
        ),
    ]
