# Generated by Django 3.2.25 on 2024-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0004_auto_20240423_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeid', models.CharField(max_length=50)),
                ('deltatime', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
