# Generated by Django 5.0.1 on 2024-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherViewer", "0005_auto_20240423_1829"),
    ]

    operations = [
        migrations.CreateModel(
            name="bulletinData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tid", models.IntegerField()),
                ("content", models.TextField()),
            ],
        ),
    ]
