# Generated by Django 5.0.1 on 2024-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherViewer", "0007_bulletindata_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="weatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_id", models.IntegerField()),
                ("upper_content", models.TextField()),
                ("lower_content", models.TextField()),
                ("update_date", models.DateField()),
            ],
        ),
    ]
