# Generated by Django 3.2.25 on 2024-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('belongs_to', models.CharField(max_length=10)),
                ('from_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField()),
                ('city', models.CharField(max_length=10)),
                ('low_temperature', models.IntegerField()),
                ('high_temperature', models.IntegerField()),
                ('morning_weather', models.CharField(max_length=10)),
                ('morning_wind_direction', models.CharField(max_length=10)),
                ('morning_wind_power', models.CharField(max_length=10)),
                ('evening_weather', models.CharField(max_length=10)),
                ('evening_wind_direction', models.CharField(max_length=10)),
                ('evening_wind_power', models.CharField(max_length=10)),
            ],
        ),
    ]
