# Generated by Django 3.2.25 on 2024-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_updated', models.DateField()),
                ('weather_update', models.DateField()),
                ('bullteins_update', models.DateField()),
                ('graphs_update', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='indexs',
            name='father_url',
            field=models.URLField(default='https://weather.cma.cn/'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='data_time',
            field=models.DateField(),
        ),
    ]
