# Generated by Django 3.2.25 on 2024-04-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0005_auto_20240423_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmid', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('img', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('url', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('high_temp', models.IntegerField()),
                ('m_weather_name', models.CharField(max_length=10)),
                ('m_weather_img', models.CharField(max_length=3)),
                ('m_wind_direction', models.CharField(max_length=5)),
                ('m_wind_power', models.CharField(max_length=5)),
                ('low_temp', models.IntegerField()),
                ('w_weather_name', models.CharField(max_length=10)),
                ('w_weather_img', models.CharField(max_length=3)),
                ('w_wind_direction', models.CharField(max_length=5)),
                ('w_wind_power', models.CharField(max_length=5)),
                ('belongs', models.CharField(max_length=5)),
                ('postid', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='CityInfo',
        ),
    ]
