# Generated by Django 3.2.25 on 2024-04-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherViewer', '0006_auto_20240425_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSignData',
            fields=[
                ('weathersigndata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WeatherViewer.weathersigndata')),
            ],
            bases=('WeatherViewer.weathersigndata',),
        ),
    ]
